version: '3.4'
services:
  website:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: health-insurance
    environment:
      NODE_ENV: production
    ports:
      - 443:443
