name: Deploy app on port 80

on:
  push:
    branches:
      - main
      - Alex/Terraform
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-portal.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-session-name: deploy-backend-session
        aws-region: ${{secrets.AWS_REGION}}

    - name: Generate .env
      run: |
          cd frontend
          echo "PORT_LOCAL=80" > .env 
          echo "MODE=production" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME}}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME}}" >> .env
          echo "DB_ENDPOINT=${{ secrets.DB_ENDPOINT}}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION}}" >> .env
          echo "PORTAL_URL=${{secrets.PORTAL_URL}}" >> .env
          echo "API_URL=${{secrets.API_URL}}" >> .env

    - name: Package artifact
      run: zip -r ./frontend.zip .env .dockerignore *
      working-directory: frontend

    - name: list files
      run: |
          cd frontend
          ls -la
          
    - name: Upload artifact to S3
      run: |
        cd frontend
        aws s3 cp frontend.zip s3://${{ secrets.BUCKET_NAME_PORTAL }}/application-${{ github.run_id }}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: deploy-server-session
          aws-region: ${{secrets.AWS_REGION}}

      - name: Stop Existing Environment (Optional)
        run: aws elasticbeanstalk stop-environment --environment-name ${{ secrets.WEB_ENV_NAME }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.WEB_APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="${{ secrets.BUCKET_NAME_PORTAL }}",S3Key="application-${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.WEB_APP_NAME }} --environment-name ${{ secrets.WEB_ENV_NAME }} --version-label ${{ github.run_id }}
